# This file stores setting to be used in all modules.

# All variables that have anything to do with diplaying should be multiples of 20 to represent the actual pixels on the matrix
SCREEN_WIDTH = 640 # The screen has to be seen as 32 20x20 pixels
SCREEN_HEIGHT = 640
PIXEL_WIDTH = 20 # Single pixel
DOWNWARD_PIXEL_PULL_OFFSET = 5
BLOCK_SIZE = 40

# Startscreen
SCREEN_HALF = SCREEN_WIDTH // 2

# Score
SCORE_POSITION_Y = PIXEL_WIDTH # One Pixel down
SCORE_POSITION_X = (SCREEN_WIDTH // 2) - (4 * PIXEL_WIDTH)

# Snake
SNAKE_SPEED = 10 # tickrate

# Doodle Jump
DJ_PLAYER_WIDTH = 2 * PIXEL_WIDTH
DJ_PLAYER_HEIGHT = 2 * PIXEL_WIDTH
DJ_JUMP_HEIGHT = 50
DJ_GRAVITY = 2
DJ_PLATFORM_WIDTH = 5 * BLOCK_SIZE
DJ_PLATFORM_HEIGHT = 2 * PIXEL_WIDTH
DJ_PLATFORM_SPACING = 12 * PIXEL_WIDTH
DJ_SPEED = 30
DJ_InputDelay = 0.03
GROUND_HEIGHT = 4 * PIXEL_WIDTH

# Dino
DINO_WIDTH  = 5 * PIXEL_WIDTH
DINO_HEIGHT = 5 * PIXEL_WIDTH
DINO_X = 6 * PIXEL_WIDTH
DINO_GRAVITY = 1
DINO_JUMP_FORCE = 25
CACTUS_WIDTH = 2 * PIXEL_WIDTH
CACTUS_MIN_HEIGHT = 3 * PIXEL_WIDTH
CACTUS_MAX_HEIGHT = 7 * PIXEL_WIDTH
CACTUS_MIN_DISTANCE = 1 * PIXEL_WIDTH
CACTUS_MAX_DISTANCE = 30 * PIXEL_WIDTH
GAME_SPEED = PIXEL_WIDTH
DINO_FPS = 30

# Tetris
TETRIS_CELL = BLOCK_SIZE
TETRIS_COLS = 10
TETRIS_OFFSET_Y = 0
TETRIS_ROWS = (SCREEN_HEIGHT - TETRIS_OFFSET_Y) // TETRIS_CELL
TETRIS_OFFSET_X = (SCREEN_WIDTH - (TETRIS_COLS * TETRIS_CELL)) // 2

SCORE_POSITION_X_TETRIS = TETRIS_OFFSET_X - 5 * PIXEL_WIDTH  
SCORE_POSITION_Y_TETRIS = BLOCK_SIZE

TETRIS_NEXT_SIZE = TETRIS_CELL // 2
TETRIS_NEXT_SPACING = 10
TETRIS_NEXT_OFFSET_X = TETRIS_OFFSET_X + TETRIS_COLS * TETRIS_CELL + 20
TETRIS_NEXT_OFFSET_Y = 120
TETRIS_NEXT_SLOT_HEIGHT = 4

TETRIS_HOLD_OFFSET_X = TETRIS_NEXT_OFFSET_X
TETRIS_HOLD_OFFSET_Y = TETRIS_NEXT_OFFSET_Y - (TETRIS_NEXT_SLOT_HEIGHT * TETRIS_NEXT_SIZE + 20)

TETRIS_FALL_SPEED = 30

# Mario
MARIO_WORLD = "Mario/1.json"
SCROLL_BORDER = SCREEN_WIDTH * 0.6

BASE_SPEED = 1          
MAX_SPEED_MULTIPLIER = 2
ACCEL_TIME = 5

MOVE_INPUT_DELAY = 0.01

SPAWN_TILE_X = 6                        
SPAWN_TILE_Y = 10                       

GRAVITY = 50 * PIXEL_WIDTH              
JUMP_VELOCITY = 35 * PIXEL_WIDTH        
MAX_FALL_SPEED = 1000
INPUT_DELAY = 0.03