# This file stores setting to be used in all modules.

# All variables that have anything to do with diplaying should be multiples of 20 to represent the actual pixels on the matrix
SCREEN_WIDTH = 640 # The screen has to be seen as 32 20x20 pixels
SCREEN_HEIGHT = 640
PIXEL_WIDTH = 20 # Single pixel
DOWNWARD_PIXEL_PULL_OFFSET = 5
BLOCK_SIZE = 40

# Startscreen
SCREEN_HALF = SCREEN_WIDTH // 2

# Score
SCORE_POSITION_Y = PIXEL_WIDTH # One Pixel down
SCORE_POSITION_X = (SCREEN_WIDTH // 2) - (4 * PIXEL_WIDTH)

# Snake
SNAKE_SPEED = 10 # tickrate

# Doodle Jump
DJ_PLAYER_WIDTH = 2 * PIXEL_WIDTH
DJ_PLAYER_HEIGHT = 2 * PIXEL_WIDTH
DJ_JUMP_HEIGHT = 50
DJ_GRAVITY = 2
DJ_PLATFORM_WIDTH = 5 * BLOCK_SIZE
DJ_PLATFORM_HEIGHT = 2 * PIXEL_WIDTH
DJ_PLATFORM_SPACING = 12 * PIXEL_WIDTH
DJ_SPEED = 30
GROUND_HEIGHT = 4 * PIXEL_WIDTH

# Dino
DINO_WIDTH = 2 * PIXEL_WIDTH
DINO_HEIGHT = 4 * PIXEL_WIDTH
DINO_X = 6 * PIXEL_WIDTH
DINO_GRAVITY = 1
DINO_JUMP_FORCE = 25

# Cactus
CACTUS_WIDTH = 2 * PIXEL_WIDTH
CACTUS_MIN_HEIGHT = 3 * PIXEL_WIDTH
CACTUS_MAX_HEIGHT = 7 * PIXEL_WIDTH
CACTUS_MIN_DISTANCE = 1 * PIXEL_WIDTH
CACTUS_MAX_DISTANCE = 100* PIXEL_WIDTH


GAME_SPEED = PIXEL_WIDTH
DINO_FPS = 30
